---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=gamechat.conf dest=/etc/init/gamechat.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=gamechat state=restarted
