---

- name: Deploy Django Application to Web Servers
  hosts: tag_Name_ansible-built
  remote_user: ubuntu
  gather_facts: yes

  roles:
    - role: django
    - role: gunicorn
    - role: jdauphant.nginx
      sudo: yes
      nginx_sites:
        default:
          - listen 80
          - server_name "{{ ec2_public_dns_name }}"
          - access_log "/var/log/nginx/django.log"
          - location / {
              proxy_pass http://127.0.0.1:8000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
          - location /static/ { root {{ django_home }}/imager/; }
          - location /media/ { root {{ django_home }}/imager/; }

