keypair: nbeck
security_group: vpc-ssh-access
instance_type: t1.micro
ami: ami-810a2fb1
vpc_subnet_id: subnet-30812047
region: us-west-2
instance_tags: {"Name": "ansible-built"}
root_ebs_size: 8
zone: us-west-2b
instance_profile_name:
num_instances: 1
